### ISSUE TITLE
Sending POST request is not working as expected

### ISSUE THREAD

**Issue by gaghan430** [mahdaen/metal-data#1]
so the issue is when I tried to make POST request using `collection.create(payload)`, 
somehow the payload was not being sent properly to API (no payload at all)
![image](https://user-images.githubusercontent.com/7876213/116265594-720f9b80-a7a5-11eb-8b5b-3da5897ad0a6.png)

**Comment by mahdaen** [comment]
@gaghan430 It should be fixed on the yesterday release. Closing it, thanks!
